### ISSUE TITLE
StorePostgresql object has no attribute log

### ISSUE THREAD

**Issue by DonovanMaillard** [lpoaura/GN2PG#17]
Hi, 

I'm testing gn2pg app, 

Setup and config file init were OK, but launching gn2pg_cli --full returns error : 

Traceback (most recent call last):
  File "/home/geonatureadmin/venv/bin/gn2pg_cli", line 8, in <module>
    sys.exit(run())
  File "/home/geonatureadmin/venv/lib/python3.9/site-packages/gn2pg/main.py", line 201, in run
    return main(sys.argv[1:])
  File "/home/geonatureadmin/venv/lib/python3.9/site-packages/gn2pg/main.py", line 191, in main
    full_download(cfg_ctrl)
  File "/home/geonatureadmin/venv/lib/python3.9/site-packages/gn2pg/helpers.py", line 101, in full_download
    full_download_1source(Data, cfg)
  File "/home/geonatureadmin/venv/lib/python3.9/site-packages/gn2pg/helpers.py", line 81, in full_download_1source
    downloader.store()
  File "/home/geonatureadmin/venv/lib/python3.9/site-packages/gn2pg/download.py", line 88, in store
    self._backend.log(
AttributeError: 'StorePostgresql' object has no attribute 'log'

**Comment by lpofredc** [comment]
Fixed with https://github.com/lpoaura/GN2PG/commit/10316c185af212411d45ae97b6a96efccf23f759.

To update, `pip install --upgrade gn2pg-client`

**Comment by DonovanMaillard** [comment]
Merci :) problème réglé, j'en ai un nouveau qui a suivi dans un ticket distinct :)
