### ISSUE TITLE
Erreur en fin d'update sur 'total_filtered'

### ISSUE THREAD

**Issue by lpofredc** [lpoaura/GN2PG#49]
La fin des update se termine sur une erreur du à la clé `total_filtered` manquante dans l'API de log des DELETE, présente dans la version initiale qui s'appuyait sur la class 'GenericQuery' de Utils-flask-SQLAlchemy.

https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/blob/bb84968353982951fd24d47e815a104df7322521/src/utils_flask_sqla/generic.py#L284-L290.

```log
2023-08-31 23:07:56,778 - DEBUG - store_postgresql:__exit__ - Closing database connection at exit from StorePostgresql
Traceback (most recent call last):
  File "/home/lpoaura/.local/bin/gn2pg_cli", line 8, in <module>
    sys.exit(run())
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/main.py", line 194, in run
    return main(sys.argv[1:])
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/main.py", line 187, in main
    update(cfg_ctrl)
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/helpers.py", line 138, in update
    update_1source(Data, cfg)
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/helpers.py", line 118, in update_1source
    downloader.update()
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/download.py", line 259, in update
    deleted_pages = self._api_instance.page_list(
  File "/home/lpoaura/.local/lib/python3.9/site-packages/gn2pg/api.py", line 189, in page_list
    total_filtered = resp["total_filtered"]
KeyError: 'total_filtered'
```

![Screenshot 2023-09-07 at 16-27-54 https __geonature lpo-aura org](https://github.com/lpoaura/GN2PG/assets/22891423/b43ef814-cb60-476b-be18-241d6498ad4e)

**Comment by camillemonchicourt** [comment]
Corrigé avec la version 0.3.6 de Utils-Flask-SQLAlchemy, intégrée à GN 2.13.1, ou à mettre à jour manuellement.
Voir https://github.com/PnX-SI/Utils-Flask-SQLAlchemy/issues/40
